
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Mnemonic250.com')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->Server('static') . 'favicon.ico'))
                    ->prependStylesheet($this->Server('static') . 'css/responsive.css')
                    ->prependStylesheet($this->Server('static') . 'css/main.css')
                    ->prependStylesheet($this->Server('static') . 'css/reset.css')
                    ->prependStylesheet($this->Server('static') . 'css/colorbox.css')
                    ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic')
                    ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
      ->prependFile($this->Server('static') . 'js/scripts.js')
      ->prependFile($this->Server('static') . 'js/jquery.colorbox.js')
      ->prependFile($this->Server('static') . 'js/jquery-1.7.2.min.js')
    ; ?>
</head>
