<section>
	<div class="ct-btn wp-ct">
		<h1>
			<strong>Lamentamos informarte que no tenemos tu documento.</strong>
		</h1>
	</div>

	<div class="wp-ct center-ct group">
		<div class="one-col small-ct">
			<p>Si deseas que te notifiquemos si un ciudadano honesto reportó tu
				documento, ingresa tu mail y número de celular para contactarte.</p>
			<form class="form-registro">
				<input type="text" placeholder="Nombre" /> <input type="text"
					placeholder="Correo electrónico" /> <input type="text"
					placeholder="Celular" /> <input class="big-btn blue-btn"
					type="button" value="Notificarme" />
			</form>
		</div>
	</div>
</section>