<section>
	<div class="center-ct">
		<div class="ct-btn wp-ct top-ct">
			<h1>
				Felicidades, han reportado tu <strong><?php echo $this->data['tipd_nombre'] .':'.$this->data['doc_numero']?></strong>
			</h1>
		</div>

		<div class="wp-ct group top-ct">
			<div class="three-col">
				<img class="list-img" src="<?php echo $this->Server('static') ?>img/ciudadano-reporto-tu-documento.png"
					title="Un ciudadano reportó tu documento"
					alt="Un ciudadano reportó tu documento" />
				<p>Un ciudadano honesto reportó tu documento, y tenemos que
					premiarlo, por lo que puedes pagar online la suma de $80.000 pesos.</p>
			</div>

			<div class="three-col middle-item">
				<img class="list-img"
					src="<?php echo $this->Server('static') ?>img/notificacion-servicio-de-mensajeria.png"
					title="El servicio de mensajería será reportado"
					alt="El servicio de mensajería será reportado" />
				<p>Luego del pago, se notifica inmediatamente al servicio de
					mensajería para que se entregue el documento a domicilio.</p>
			</div>

			<div class="three-col">
				<img class="list-img" src="<?php echo $this->Server('static') ?>img/regalanos-tu-testimonio.png"
					title="Regalanos tu testimonio del servicio en nuetras redes"
					alt="Regalanos tu testimonio del servicio en nuetras redes" />
				<p>Regálanos un testimonio del buen servicios que te brindamos en
					nuestras redes sociales.</p>
			</div>
		</div>

		<div class="ct-btn wp-ct">
			<a href="#" class="yellow-btn big-btn">Premiar al honesto</a>
		</div>
	</div>
</section>