<section>
	<div class="ct-btn wp-ct">
		<h1>
			<strong>Lamentamos informarte que no tenemos tu documento.</strong>
		</h1>
	</div>

	<div class="wp-ct center-ct group">
		<div class="one-col small-ct">
			<p>Si deseas que te notifiquemos si un ciudadano honesto reportó tu
				documento, ingresa tu mail y número de celular para contactarte.</p>
			<form class="form-registro" id="formregidtro">
				<input type="text" placeholder="Nombre" name="nombre" /> 
				<input type="text" placeholder="Correo electrónico" name="email" /> 
				<input type="text" placeholder="Celular" name="movil" /> 
				<input type="hidden" name="tipo" />
				<input type="hidden" name="numdoc" value="<?php echo $this->numdoc ?>" /> 
				<input class="big-btn blue-btn" type="button" value="Notificarme" onclick="guardarDocumento()" />
			</form>
		</div>
	</div>
</section>

<script>
function guardarDocumento() 
{
    $.ajax({
    	  url: "/application/index/guardar-documento",
    	  data : $('#formregidtro').serialize(),
    	  type : 'POST',
    	  beforeSend: function( xhr ) {
    	    xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
    	  }
    	}).done(function( data ) 
    	{
            
      });
}
</script>