<section>
	<div class="center-ct">
		<div class="wp-ct top-ct">
			<h1>
				<strong>¿Perdiste tus documentos?</strong> Encuéntralos en <span>Budocu</span>
			</h1>
			<div class="input-ct">
				<form method="post" action="">
					<input type="text" placeholder="Busqueda de documentos" name="search" /> <input
						type="button" />
				</form>
			</div>
		</div>

		<div class="wp-ct bottom-ct group">
			<div class="two-col">
				<h2>¿Encontraste un documento?</h2>
				<p>Sí encontraste un documento, ayuda a quién lo está buscando y en
					Budocu te recompensamos.</p>
			</div>
			<div class="two-col last-item">
				<a href="/reportar-documento" class="yellow-btn big-btn">¡Encontré un documento!</a>
			</div>
		</div>
	</div>
</section>

<aside>
	<div class="wp-ct">
		<iframe class="mapa-home"
			src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d991.6426318554041!2d-75.57706668582549!3d6.188181430446238!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e4428ef4e52dddb%3A0x722fd6c39270ac72!2sMedell%C3%ADn%2C+Antioquia%2C+Colombia!5e0!3m2!1ses!2sit!4v1443132721844"
			frameborder="0" style="border: 0" allowfullscreen></iframe>
	</div>
</aside>
