<section>
	<div class="center-ct wp-ct group">
		<div class="wp-ct group center-ct">

			<div class="two-col">
				<h2>Regálanos tus datos</h2>
				<form class="form-datos form-registro">
					<select>
						<optgroup>
							<option>Tipo de documento</option>
							<option>Cédula de ciudadanía</option>
							<option>Tarjeta de identidad</option>
							<option>Pasaporte</option>
							<option>Tarjeta de residencia</option>
						</optgroup>
					</select> <input type="text" placeholder="Número de documento" /> <input
						type="text" placeholder="Email" /> <input type="text"
						placeholder="Móvil" /> <label> <input type="checkbox">
					<p>
							Acepto los <a href="#terminos-condiciones"
								class="inline cboxElement">términos y condiciones</a>
						</p>
					</label>
				</form>
			</div>

			<div class="two-col last-item">
				<h2>¿Dónde lo encontraste?</h2>
				<div class="wp-ct">
					<iframe class="inside-map"
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d991.6426318554041!2d-75.57706668582549!3d6.188181430446238!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e4428ef4e52dddb%3A0x722fd6c39270ac72!2sMedell%C3%ADn%2C+Antioquia%2C+Colombia!5e0!3m2!1ses!2sit!4v1443132721844"
						frameborder="0" style="border: 0" allowfullscreen></iframe>
				</div>
			</div>
		</div>

		<div class="ct-btn wp-ct">
			<a class="big-btn"
				href="/documento-reportado">Quiero regresar un documento</a>
		</div>

	</div>

</section>